trigger:
- development

resources:
- repo: self

variables:
- name: dockerRegistryServiceConnection
  value: 'bceecb35-009a-48ed-a048-588a5bd4c016'
- name: imageRepository
  value: 'orygenadminui'
- name: containerRegistry
  value: 'heartburstacr.azurecr.io'
- name: dockerfilePath
  value: '**/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
  # Agent VM image name
- name: vmImageName
  value: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: replacetokens@3
      inputs:
        rootDirectory: '$(Build.SourcesDirectory)'
        targetFiles: |
          **/*.json
          **/*.yml
          **/*yaml
          **/.env.*
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTransforms: false
        enableTelemetry: true
